const styles = {
    container: {
      minHeight: "100vh",
      background: "linear-gradient(135deg, #f8fafc 0%, #ffffff 50%, #f1f5f9 100%)",
      padding: "24px",
      fontFamily:
        '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    },
    title: {
      fontSize: "2.5rem",
      fontWeight: "700",
      background: "linear-gradient(135deg, #059669 0%, #0d9488 100%)",
      WebkitBackgroundClip: "text",
      backgroundClip: "text",
      WebkitTextFillColor: "transparent",
      marginBottom: "8px",
    },
    subtitle: {
      color: "#6b7280",
      fontSize: "1.125rem",
      marginBottom: "32px",
    },
    form: {
      background: "#ffffff",
      borderRadius: "16px",
      padding: "32px",
      maxWidth: "500px",
      marginBottom: "32px",
      boxShadow: "0 10px 15px -3px rgba(0, 0, 0, 0.1)",
      border: "1px solid #f3f4f6",
    },
    input: {
      padding: "12px 16px",
      fontSize: "1rem",
      border: "1px solid #e5e7eb",
      borderRadius: "8px",
      marginBottom: "16px",
      width: "100%",
      outline: "none",
    },
    textarea: {
      padding: "12px 16px",
      fontSize: "1rem",
      border: "1px solid #e5e7eb",
      borderRadius: "8px",
      marginBottom: "16px",
      width: "100%",
      minHeight: "100px",
      resize: "vertical",
      outline: "none",
    },
    button: {
      padding: "12px 24px",
      background: "linear-gradient(135deg, #059669 0%, #0d9488 100%)",
      color: "#ffffff",
      fontWeight: "600",
      fontSize: "1rem",
      borderRadius: "8px",
      border: "none",
      cursor: "pointer",
    },
    message: (isSuccess) => ({
      textAlign: "center",
      fontWeight: "600",
      color: isSuccess ? "#059669" : "#dc2626",
      marginBottom: "24px",
    }),
    resume: {
      display: "flex",
      justifyContent: "space-between",
      marginBottom: "24px",
      background: "#ecfdf5",
      padding: "16px 24px",
      borderRadius: "12px",
      border: "1px solid #d1fae5",
      boxShadow: "0 4px 6px -1px rgba(0,0,0,0.05)",
    },
    grid: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fill, minmax(350px, 1fr))",
      gap: "24px",
    },
    card: {
      background: "#ffffff",
      borderRadius: "16px",
      boxShadow: "0 10px 15px -3px rgba(0, 0, 0, 0.1)",
      border: "1px solid #f3f4f6",
      padding: "24px",
    },
    cardTitle: {
      fontSize: "1.25rem",
      fontWeight: "700",
      color: "#1f2937",
      marginBottom: "12px",
    },
    cardDescription: {
      color: "#6b7280",
      fontSize: "0.875rem",
      marginBottom: "20px",
    },
    priceValue: {
      fontSize: "1.125rem",
      fontWeight: "700",
      color: "#059669",
    },
    messageSuccess: {
      padding: "10px",
      backgroundColor: "#d1fae5",
      color: "#065f46",
      borderRadius: "8px",
      fontWeight: "600",
    },
    messageError: {
      padding: "10px",
      backgroundColor: "#fee2e2",
      color: "#991b1b",
      borderRadius: "8px",
      fontWeight: "600",
    },
  };
  
  export default styles;
  